import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css';
import { Container, Theme } from '@radix-ui/themes'
import Navbar from './Navbar'
import AuthProvider from './auth/Provider'
import { Playfair_Display } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })

const play = Playfair_Display({ 
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-play'

})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${play.variable}`}>
      <body className={inter.className}>
      <AuthProvider>
      <Theme accentColor="violet" appearance="light">
        <Navbar />
      <main className="px-5">
                <Container>{children}</Container>
        </main>
        </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
